### ISSUE TITLE
2019 POM Particulate Organic Matter

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/iys-oos#10]
Description: 
Source Language: English
Status: Processed & available as spreadsheet
Group: UBC
Data Access: NONE

**Comment by jclgan** [comment]
What's the difference between Depth and Sample depth?

**Comment by jclgan** [comment]
Is `Volume filtered` in L?

**Comment by jclgan** [comment]
No metadata on what each of the sheets represent. `Sheet2` appears to be a copy of `Sheet1`, but missing one sample ("P45"). `Sheet3` looks to be a subset of `Sheet1`, minus a few columns, but the values for d13CVPDB and d15NAir are different.

**Comment by jclgan** [comment]
Timezone unknown
