### ISSUE TITLE
2019 HPLC

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/iys-oos#11]
Description: NONE
Source Language: English
Status: Processed & available as a spreadsheet
Group: UVic
Data Access: None

**Comment by timvdstap** [comment]
@Br-Johnson Is this an active issue / is the dataset available to us?

**Comment by Br-Johnson** [comment]
I imagine Brian will know.

**Comment by timvdstap** [comment]
My bad, completely overlooked this issue when I created the new one. I asked Brian and he said that Maycira's group is responsible for the data processing. I've sent her an email inquiring about the status of the data. Will therefore close this issue.
