### ISSUE TITLE
Create documentation for best practices for Darwin Core data transformation

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/iys-oos#14]
# Darwin Core
## How to convert data to Darwin Core Archive OBIS flavour for various science domains https://obis.org/manual/

TODO:
[x] Copy example script from IOOS/bio-data-guide
[x] Make Public the Bio Data Guide on IOOS' GitHub  
[x] Establish this doc as my brain dump that might one day be useful
[ ]

**Comment by Br-Johnson** [comment]
Most of the documentation is currently maintained in https://github.com/ioos/bio_data_guide/tree/master/docs/Standardizing%20Marine%20Biological%20Data

This is an important document to maintain, when we move into more communications related activities.

**Comment by Br-Johnson** [comment]
@timvdstap @jclgan Once you guys have a couple of .Rmd files from your transformations, let me know so I can add them to the Bio Data Guide.

**Comment by Br-Johnson** [comment]
see https://ioos.github.io/bio_data_guide/intro.html

**Comment by timvdstap** [comment]
> @timvdstap @jclgan Once you guys have a couple of .Rmd files from your transformations, let me know so I can add them to the Bio Data Guide.

@Br-Johnson I think the standardization .Rmd files currently in the develop branch are fairly 'finalized' (although of course we haven't tried uploading anything to ERDDAP or OBIS yet, so there might be future changes). For now, those are the most up to date transformation files we have and could perhaps be used in the Bio Data Guide.

**Comment by Br-Johnson** [comment]
OK. Great. Let's keep them in here for now. I've provided the Hakai JSP spp. occurrences to the IOOS group so we'll be good until we figure out what's happening with the ESIP Bio Data Cluster and the upcoming update on Standardizing Marine Biolgical Data with Abby and Vicky.

**Comment by Br-Johnson** [comment]
Otherwise, you could make a release into the master branch only the .Rmd files that are finalized. Make sure there's no sensitive info in there first and you should be good.
