### ISSUE TITLE
2019 Salmon Diets

### ISSUE THREAD

**Issue by jclgan** [HakaiInstitute/iys-oos#19]
Description:
Source Language: English
Status: Processed and available as spreadsheet
Group: UBC
Data Access: None

**Comment by jclgan** [comment]
What is the column `N Stomachs`?

**Comment by Br-Johnson** [comment]
I would assume it means number of stomachs.

**Comment by Br-Johnson** [comment]
Is this a duplicate issue?

**Comment by timvdstap** [comment]
Sorry, only see this now (quite frankly I didn't notice there was a second page to the Issue tab *derp*) - there is a duplicate (though more encompassing) issue created: #60 I'll close this issue.
