### ISSUE TITLE
Bottle File

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/iys-oos#23]
Description: A view of CTD data joined to discrete depths where water was collected in a bottle (niskin).

**Comment by Br-Johnson** [comment]
After @jclgan and @timvdstap cycled through their first round of DwC transformations, we came to the conclusion that it really only makes sense to transform nutrients, oxygen, CTD, and POM into DwC and then rebuild as a 'bottle-file' of discrete depths.

**Comment by timvdstap** [comment]
Update on the creation of the bottle file. I've been in touch with Jessy on how best to go about creating a bottle file. Current steps required for the CTD data are:

1. .hex, .con, and .psa files are required to get .cnv file and .ros file as output. Cast-specific .cnv files have been generated and provided to us, .ros files haven't.
2. .ros, .psa and .con files are required to create a .btl file. 
3. .cnv and .btl file are needed to create a NetCDF file, which can then be hosted on ERDDAP. 

Current problem that we're having is that I don't have the **.ros** files. While we can create these with the .hex and .CON files that we **do** have, I noticed that the .cnv files that also get generated in this process indicated that the .CON file (= configuration) that was used in the process was **0964_9.con**. We do not have this file, we only have cast-specific .con files (i.e., ka61_043.con). Therefore, I have asked Anna to ensure that the information in the 0964_9 and cast-specific .con files matches. _If_ this is the case, then we can generate the **.ros** files and proceed with trying to generate the bottle files.

**Comment by Br-Johnson** [comment]
@timvdstap Do we still plan on creating a bottle file? Or rather just hosting the individual data sets that others would use to build their own bottle file? I might suggest the latter

**Comment by timvdstap** [comment]
@Br-Johnson Yeah we should close this issue, I think we should prioritize hosting individual data sets as well. That's challenging enough as it is ;-)
