### ISSUE TITLE
Publish (meta)Data

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/iys-oos#24]
For all data elements, generate appropriate and valid metadata records and
insert them into the metadata catalogue on the IYS Data Catalogue, so that they are
discoverable by IYS users. Metadata should be prioritized and filled out in the IYS CKAN Data catalogue as soon as the minimum required fields are complete. When data sets are complete, publish datasets by providing a link to where the data are hosted, from the metadata catalogue record.

**Comment by Br-Johnson** [comment]
Hey @jclgan and @timvdstap I made a template catalogue entry that we should review. Check it: https://iys.hakai.org/dataset/template

**Comment by timvdstap** [comment]
For all 2019 datasets there has now been a draft metadata record created, as well as for those 2020 data that we have received.
