### ISSUE TITLE
Occurrence Table

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/iys-oos#45]
Construct an occurrence table from the Trawl abundance and/or Bridge log.

**Comment by jclgan** [comment]
There are 55 records for which we have "catch mass" values, but individual counts (`PIECES`) is blank

**Comment by jclgan** [comment]
Hey @timvdstap , please comment here about your findings from Chrys after your call with her Monday evening :)

Thanks!

**Comment by jclgan** [comment]
Currently we only have a file that provides summary data of fish length & weight measurements (i.e., min/max length, and total weight of catch) for each trawl.

Awaiting individual-specific data from Chrys Neville.

**Comment by Br-Johnson** [comment]
@timvdstap I think this is old and irrelevant now that you've got the 2019 trawl data?

**Comment by timvdstap** [comment]
@Br-Johnson Correct, I'll close.
