### ISSUE TITLE
Event Table

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/iys-oos#46]
Construct and publish Event table from Bridge log and any other eMoF table that utilizes parentEventIDs

**Comment by jclgan** [comment]
I'm not sure whether this issue is referring to one dataset or multiple...

**Comment by Br-Johnson** [comment]
Eventually we'll  need to decompose all the events into the Darwin Core format so during that process we may have to combine multiple tables

**Comment by Br-Johnson** [comment]
This is old and irrelevant now.
