### ISSUE TITLE
Temporal discrepancy between CTD & other datasets

### ISSUE THREAD

**Issue by jclgan** [HakaiInstitute/iys-oos#57]
See branch: feature/eventDate_QC 

Chl dataset states that times are in UTC-12. CTD metadata file says time is in UTC+10. Comparing the two datasets, more than half of the CTD cast times actually match the Chl event times, even though there should be a two-hour offset. Most of the mismatches are off by only 10-20 minutes (which we're attributing to different people recording the cast times). Only one station (55) is off by about 10 hours between the two datasets. 

@timvdstap is in contact with CTD data processor Hae Kun Jung to try to get some answers.

**Comment by Br-Johnson** [comment]
Any updates on this front?

**Comment by Br-Johnson** [comment]
@timvdstap Did you ever hear back from Hae Kun Jung on this?

**Comment by Br-Johnson** [comment]
This was never adequately resolved by Hae Kun Jung. Here is the response received:

Dear Tim.

 

I can not remember clearly about it.

 But. Time information of CTD metadata was well matched with other data set (attacted file : chl concentration data).

 

and i give you some raw data of CTD (number from 42 to 52 : CTD number) please compare time information between raw data and combined data.

Time information in raw data is ship time, may be.



If you have any question about it, do not hesitate to contact me.

Kind regards,

 

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
Hae Kun Jung
