### ISSUE TITLE
Bongo Zooplankton - Questions

### ISSUE THREAD

**Issue by timvdstap** [HakaiInstitute/iys-oos#58]
# Bongo Net Zooplankton Dataset Questions

Questions:
- [X] There are two different net numbers, are these different in their dimensions? **A**: It would appear from their sampling protocol 2020 that both nets are 0.5 m2 with mesh size 0.236 mm. Will have to confirm with Brian that similar Bongo nets were used in 2019.
- [X] What exactly is meant by 'size fractions' -, and does size fraction have a measurementUnit associated? **A**: My current understanding is that a vertical bongo net was deployed at 250m depth, and towed vertically. Collected samples were sieved through different mesh sizes and then preserved at -20C before being examined in the lab. The mesh sizes are: 4000, 2000, 1000, 500 and 250 microns. 
- [X] Description / explanation needed for values found in sample type (i.e., FA/ISO) column. **A**: This column appears to indicate the type of analysis conducted on the preserved sample [need confirmation]. FA = fatty acid, ISO = isotope. As this column doesn't include any measured variables, it will not be included in the current data wrangling. Should data become available from these analyses then this column will be used.     
- [X] Description / explanation needed for values found in the Stage column (i.e., spent, or 4). **A**: This column represents different life stages for species. As there is such a wide variety of species caught, there are different descriptions of the various life stages. I am now in touch with Brian H and Natalie Mahara (responsible for the IYS 2020 Bongo data) on this topic. 
- [X] Is there an interest in the species you _didn't_ find in the Bongo net? Are you interested in both the species present, or also absent? Was there a targeted search  for a specific species? **A**: Very likely not, but will confirm with Brian. 
- [X] Is there a sampling protocol available specifying characteristics of the sampling procedure and bongo net? **A**: I've found the survey protocol for 2020, and Brian has sent me the sampling procedures from 2019.
- [X] As there is no end latitude/longitude, was it a vertical bongo net that was deployed (at depth = 250m)? **A**: Yes, vertical tow.
- [X] How to classify a species when it is listed as 'size fraction'? For all species that are 'size fraction', the group is Zooplankton, but this does not seem to have an associated URN from WoRMS? **A**: After discussion with Julian, measurements associated to species that can not be identified to species or genus level will be linked directly to the `sampleID` (which is the eventID), and these will not receive an `occurrenceID`. Species that have been identified to species or genus level can have an associated URN from WoRMS and will be included in an Occurrence Core. 
- [X] How can length type = 'total' when the Species = size fraction? Additionally, sampleID Z383: tissue = muscle, but size fraction and length are 0.25? **A**: After pers. comm. with Brian H., tissue was changed to 'whole'. 
- [X] How to handle entries where number > 1, and Length = e.g. 16 - 20 mm. Perhaps for these have eventIDs have a measurement column associated with minimum length and maximum length? **A**: Yes, there will be measurementTypes `minimum length` and `maximum length` included for these data entries.
- [X] How is the sampling effort typically measured: in length of time it took to tow the net up, or in the volume of water filtered? **A**: As per N. Mahara: _For the IYS bongo tows it was measured as volume of water filtered – there should be a flowmeter measurement that is checked against the estimated volume filtered using sample depth (250m). Typically if it’s outside a certain range (I think the Hakai standard is 40%) then the depth-estimated volume is used instead of the flowmeter calculation._
- [x] What is the samplingEffort of the Bongo tow at each station? -- Need to get the flowmeter measurement. 
- [x] Does one Bongo net by definition consist of two units? Because part of the sampling protocol reads that one only net ('unit'?) was deployed, whereas the results indicated two nets.

**Comment by Br-Johnson** [comment]
> [ ] There are two different net numbers, are these different in their dimensions?
Good question. We need ring diamter, length, net mesh size, and cod-end mesh size.
> [ ] What exactly is meant by 'size fractions' -, and does size fraction have a measurementUnit associated?
Different size fractions reflect the smallest size mesh it has been passed through. Usually we stack from 4000 to 64 micron and washdown. The arbitrary size fractions then 'represent' different communities depending on what size fractions you combine during analysis.

We need to get some key people onto this platform so they can answer these questions directly.

**Comment by timvdstap** [comment]
Agreed, there are some questions to which I now have the answer, much thanks to @jclgan ! I've answered these questions in my original post/issue -- I figured this way I can look back at these questions/answers should I ever need to. Once they've all been answered I'll resolve the issue. 

Should any questions remain unanswered I'll shoot Brian an email.

**Comment by Br-Johnson** [comment]
> # Bongo Net Zooplankton Dataset Questions
> 
> 
> 
> Questions:
> 
> - [X] There are two different net numbers, are these different in their dimensions? **A**: It would appear from their sampling protocol 2020 that both nets are 0.5 m2 with mesh size 0.236 mm. Will have to confirm with Brian that similar Bongo nets were used in 2019.
> 
> - [X] What exactly is meant by 'size fractions' -, and does size fraction have a measurementUnit associated? **A**: My current understanding is that a vertical bongo net was deployed at 250m depth, and towed vertically. Collected samples were sieved through different mesh sizes and then preserved at -20C before being examined in the lab. The mesh sizes are: 4000, 2000, 1000, 500 and 250 microns. 
> 
> - [X] Description / explanation needed for values found in sample type (i.e., FA/ISO) column. **A**: This column appears to indicate the type of analysis conducted on the preserved sample [need confirmation]. FA = fatty acid, ISO = isotope. As this column doesn't include any measured variables, it will not be included in the current data wrangling. Should data become available from these analyses then this column will be used.     
> 
> - [X] Description / explanation needed for values found in the Stage column (i.e., spent, or 4). **A**: This column represents different life stages for species. As there is such a wide variety of species caught, there are different descriptions of the various life stages. I am now in touch with Brian H and Natalie Mahara (responsible for the IYS 2020 Bongo data) on this topic. 
> 
> - [X] Is there an interest in the species you _didn't_ find in the Bongo net? Are you interested in both the species present, or also absent? Was there a targeted search  for a specific species? **A**: Very likely not, but will confirm with Brian. 
> 
> - [X] Is there a sampling protocol available specifying characteristics of the sampling procedure and bongo net? **A**: I've found the survey protocol for 2020, and Brian has sent me the sampling procedures from 2019.
> 
> - [X] As there is no end latitude/longitude, was it a vertical bongo net that was deployed (at depth = 250m)? **A**: Yes, vertical tow.
> 
> - [X] How to classify a species when it is listed as 'size fraction'? For all species that are 'size fraction', the group is Zooplankton, but this does not seem to have an associated URN from WoRMS? **A**: After discussion with Julian, measurements associated to species that can not be identified to species or genus level will be linked directly to the `sampleID` (which is the eventID), and these will not receive an `occurrenceID`. Species that have been identified to species or genus level can have an associated URN from WoRMS and will be included in an Occurrence Core. 
> 
> - [X] How can length type = 'total' when the Species = size fraction? Additionally, sampleID Z383: tissue = muscle, but size fraction and length are 0.25? **A**: After pers. comm. with Brian H., tissue was changed to 'whole'. 
> 
> - [X] How to handle entries where number > 1, and Length = e.g. 16 - 20 mm. Perhaps for these have eventIDs have a measurement column associated with minimum length and maximum length? **A**: Yes, there will be measurementTypes `minimum length` and `maximum length` included for these data entries.
> 
> - [X] How is the sampling effort typically measured: in length of time it took to tow the net up, or in the volume of water filtered? **A**: As per N. Mahara: _For the IYS bongo tows it was measured as volume of water filtered – there should be a flowmeter measurement that is checked against the estimated volume filtered using sample depth (250m). Typically if it’s outside a certain range (I think the Hakai standard is 40%) then the depth-estimated volume is used instead of the flowmeter calculation._
> 
> - [ ] What is the samplingEffort of the Bongo tow at each station? -- Need to get the flowmeter measurement. 
> 
We may have to rely on the volume calculations given to us in terms of samplingEffort. Though we should advocate for raw data access and scripted or otherwise reproducible calculations. 
> - [ ] What are the specific serial numbers for each Bongo net? 
> 
> - [ ] Does one Bongo net by definition consist of two units? Because part of the sampling protocol reads that one only net ('unit'?) was deployed, whereas the results indicated two nets. 

Thats right. It's like a bongo drum. There's only ever two in a bongo. Each a different mesh size. No one likes a mongo because you narrow the range of taxa sampled or always clog your nets up.

**Comment by timvdstap** [comment]
To do:

- [ ] Write up document for meeting with Natalie Mahara (Oct 16) to discuss learning outcomes of 2019 IYS Bongo data wrangling for the data processing of the 2020 Bongo data.

**Comment by timvdstap** [comment]
- [ ] Information on both the volume filtered and the tow distance has been provided; are both required for OBIS and how best to include both of them in the event Core / measurementOrFact core?

**Comment by timvdstap** [comment]
Reminder for future:

After a discussion with the SMBD, follow the following steps to determine if the data entry should be included in the occurrence Core:

1) Try to identify the lowest known common taxonomic rank, and put the recorded species under `vernacularName`. For example: Jellyfish spp. would go under: Animalia > Cnidaria, `vernacularName` = Jellyfish, `verbatimTaxonRank` = spp.
2) See if the data provider can shed more light on the taxons included. Perhaps they always use 'gelatinous spp.' if they can't identify the genus or species of Cnidaria. 
3) If no taxonomic information can be assigned to the species, don't include the record in the Occurrence Core, but rather assign the measurements associated to this record straight to the eventID.

**Comment by timvdstap** [comment]
Questions associated to the 2020 Bongo dataset:
- [ ] Can gelatinous spp. and Jelly (unknown) be classified to a more specific rank?
- [ ] Confirm that for sample ID G89, Number = 8.

**Comment by timvdstap** [comment]
Final processing steps to be completed for the 2019 and 2020 IYS Bongo Zooplankton data:

Add controlled vocabulary for the following terms: 
-	[ ] Sample volume as estimated by (estimated) sampling depth
-	[ ] Multitude of species’ life stages
-	[ ] Sampling instrument length
-	[ ] Abundance of bio per sampling volume [when sample volume is measured by flowmeter]
-	[ ] Abundance of bio per sampling volume [when sample volume is measured by sampling depth]

Do the following:
-	[ ] Confirm species changed with Natalie Mahara, for:
                    - [X] 2019 
                    - [ ]  2020
-	[ ] Match raw vs processed data – ensure all notes, life stages, etc pertaining to occurrences and events are recorded in the processed data
-	[ ] Finalize the OBIS-compliant metadata records. 
-	[ ] Ask Natalie, Brian and Evgeny to verify the metadata
-	[ ] Send over the tidied version of 2019 and 2020 bongo data (event, occurrence and extended measurement or fact cores) to Natalie and co. 
-	[ ] Finally publish both records in OBIS / GBIF (once papers are published?)

**Comment by timvdstap** [comment]
Following a conversation with Brian H. the 2019 & 2020 EventCore, occurrence extensions and draft metadata versions for the IYS bongo zooplankton data will be sent to Brian, Evgeny and Natalie for verification. I will aim to do this by the end of March.

**Comment by timvdstap** [comment]
Following conversation with Natalie, IYS bongo data from 2019 / 2020 can probably be aggregated!

**Comment by timvdstap** [comment]
To do:
- [ ] For the following `species`, change these to "Animalia" in the standardized data: `size fraction`, `chaetognath & ctenophore`, `jelly mass`, `jelly fish, radiolarian, chaetognath`, `gelatinous` and `ctenophore/jellyfish`. 
- [ ] If species = size fraction, and length (mm) is 0.25, 0.5, 1 or 2, this represents a minimum length. In the eMOF this length (mm) = 0.25 should be represented as minimum lenght = 0.25 mm, maximum length = 0.5 mm. 
- [ ] Notes in occurrence table should be included, perhaps as occurrenceRemarks?
