### ISSUE TITLE
2019 CTD Data

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/iys-oos#6]
Description: Sea-bird SBE. 
Source Language: Originally in Russian. 
Status: Processed & available as CSV files
Group: TINRO
Data location: Google Drive

**Comment by jclgan** [comment]
No data dictionary provided

**Comment by jclgan** [comment]
`Sheet 2` contains the entire dataset; `Sheet 1` is just a subset of `Sheet 2` of specific depths (5, 25, 50, 75, 100, 150, 200,400,600, and 1000). I have no idea what `Sheet 3` represents; likely also subsetted data from `Sheet 2`, but there are no column headings.

**Comment by jclgan** [comment]
For the most part, the Sea-bird Temperature & Salinity data from the `Hydro` spreadsheet in the Nutrients dataset all match with the SBE T&S data from the CTD dataset. However, there are 37 records (out of the 50,278 matching records) that have temp and/or sal values that do not match.

**Comment by timvdstap** [comment]
- [ ] What exactly is the difference between NO.Trawl and NO. (ST), and why does NO. (ST) not go from 1 - 60?
- [ ] Is the timezone correct?
- [ ] It appears as though BOD5 is often measured in mg/L, but in the dataset it is listed as ml/L?
- [ ] Is there a difference between the two models of CTD (Rinko and Sea-Bird) in how parameters are measured, or is the depth range the only difference?
- [ ] Turbidity is listed as FTU, though appears internationally more recognized as NTU? Is conversion required?
- [ ] There are two columns of electrical conductivity - how are they different?
- [ ] What does the column `Chl-Flu` mean? Concentration chlorophyll as measured by fluorometry?

**Comment by jclgan** [comment]
Confusingly, column Z, "Batt. [V]" implies Battery voltage; however, the metadata also calls it "Desolved Oxygen from CTD (Model : Rinko) (until 600m)" What's up with that?

**Comment by timvdstap** [comment]
> Confusingly, column Z, "Batt. [V]" implies Battery voltage; however, the metadata also calls it "Desolved Oxygen from CTD (Model : Rinko) (until 600m)" What's up with that?

I've asked Anna for clarification - I think it's a mistake in the metadata.

**Comment by timvdstap** [comment]
I've asked Anna some additional questions:

- [ ] There seems to be a difference between what Anna reported as being the Sea-Bird CTD unit and what was reported in the 2019 IYS cruise summary report. I've asked for clarification.
- [ ] I've asked how the sampling instruments were calibrated. 
- [ ] I've asked how typically the sampling effort is defined (is that the speed at which the CTD is lifted?) and whether they followed any sampling protocols described in other scientific papers.

**Comment by Br-Johnson** [comment]
Good to drill down relentlessly to the nitty gritty. Thats the job ;)

**Comment by timvdstap** [comment]
To do:

- [ ] Find the controlled vocabulary for the Rinko sampling instrument (https://www.jfe-advantech.co.jp/eng/ocean/rinko/rinko-profiler.html )

**Comment by Br-Johnson** [comment]
https://doi.org/10.21966/66gj-7q46
