### ISSUE TITLE
Illustrate Data Model conceptually

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/iys-oos#62]
## Task Description
No one ones what I'm talking about

TODO:
[ ] Review recent illustration attempts
[ ] Design sprint the data model
[ ]

**Comment by timvdstap** [comment]
Leaving a note here as I have attempted to illustrate the data model conceptually using LucidChart (recommended by Ray): 
https://lucid.app/documents#/dashboard?folder_id=home

**Comment by Br-Johnson** [comment]
We've got a solid array of data model conceptualizations now here: https://lucid.app/documents#/documents?folder_id=237601716

So, I'm going to call this good!
