### ISSUE TITLE
DMP - Subset Historic Salmon Diet data

### ISSUE THREAD

**Issue by timvdstap** [HakaiInstitute/iys-oos#67]
Write up a data management plan (DMP) for a subset of historical salmon diet data. Once the DMP is agreed on, it can be applied to a small subset of the historical salmon diet data that Caroline Graham has been working to visualize/demonstrate the workflow and results. The DMP should include:

- Describe the federated approach taken and data platforms used; 
- Visual representation of relational database structures;
- Describe the vision / principles upon which the work gets done (FAIR / TRUSTed);
- Describe if/how the workflow adds to the sustainability of the data (moving forward, how will be the data be useful);
- ...

**Comment by timvdstap** [comment]
Questions associated to DMP:

[ ] Is this document more of a Data Management Plan or Data Mobilization and Communication Plan?
[ ] Should we comment on the interoperability of the historic salmon diet data with the IYS project?
[ ] Does OBIS extract data from e.g. ERDDAP or do we host the transformed data _both_ on ERDDAP (wide format) and OBIS (long format)?

**Comment by timvdstap** [comment]
On Aug 27, discussed with Brian & @mcarolinegraham the following: 

- [X] We'll create a feature/branch off of the develop branch for historicSalmondiet data and scripts. 
- [ ] Caroline will pick two subsets (source-ids) from her database and write the initial .Rmd script on how to extract the different elements from her database on GitHub. We'll make sure that these source-ids have two different quality levels of metadata associated to them, to give us an idea of the quality range of the metadata in the database.
- [ ] I will create the event and occurrence cores for the two source-ids, and host the script in the feature/branch so that Caroline can easily follow the progress and process should she want to. 

@Br-Johnson for these two subsets, should I create metadata entries in our CKAN catalogue? Brian said he was ok with being the point of contact. Maybe we can discuss some of the other metadata entries & the DMP in a zoom chat sometime soon?

**Comment by Br-Johnson** [comment]
> Questions associated to DMP:
> 
> 
> 
> [ ] Is this document more of a Data Management Plan or Data Mobilization and Communication Plan?

Probably the latter!


> [ ] Should we comment on the interoperability of the historic salmon diet data with the IYS project?

I think so yes. This workflow could be a concise example of data integration/rescue operation
> [ ] Does OBIS extract data from e.g. ERDDAP or do we host the transformed data _both_ on ERDDAP (wide format) and OBIS (long format)?

Detailed oceanographic data (CTD profiles, pigment analyses, nutrient profiles) goes onto ERDDAP, summary ENV data goes into OBIS, for the time being.

**Comment by Br-Johnson** [comment]
> On Aug 27, discussed with Brian & @mcarolinegraham the following: 
> 
> 
> 
> - [X] We'll create a feature/branch off of the develop branch for historicSalmondiet data and scripts. 
> 
> - [ ] Caroline will pick two subsets (source-ids) from her database and write the initial .Rmd script on how to extract the different elements from her database on GitHub. We'll make sure that these source-ids have two different quality levels of metadata associated to them, to give us an idea of the quality range of the metadata in the database.
> 
> - [ ] I will create the event and occurrence cores for the two source-ids, and host the script in the feature/branch so that Caroline can easily follow the progress and process should she want to. 
> 
> 
> 
> @Br-Johnson for these two subsets, should I create metadata entries in our CKAN catalogue? Brian said he was ok with being the point of contact. Maybe we can discuss some of the other metadata entries & the DMP in a zoom chat sometime soon?

Yes, good idea to make the metadata entries ASAP. Lets get the metadata correct and full right off the bat to show a nice example.

**Comment by timvdstap** [comment]
As I am now finishing up with the data wrangling for the two source_id's and we've sent out the DMAC to Brian/Dick, I think we can close this issue.
