### ISSUE TITLE
Paper - Salmon as Sampling Instrument

### ISSUE THREAD

**Issue by timvdstap** [HakaiInstitute/iys-oos#68]
We briefly  touched on this during a discussion with Brian, and I figured I'd make an issue to get the ball rolling. Perhaps not closely related to the IYS project, but I see merit in writing up a scientific paper on how salmon can be used as a "sampling instrument" for their direct marine environment. I would love to take a lead on this if we see merit in it. Would love to hear thoughts.

TODO:
- [ ] Discuss possibilities with Brett / Brian: will paper be useful scientific contribution?
- [ ] Salmon as sampling instrument for marine environment through: stomach content, pathogens, sea lice (+ ?? )
- [ ] Case studies: (historic) salmon diet (stomach content) data, pathogen load, sea lice.

**Comment by Br-Johnson** [comment]
I think this would fit in with the proposal that Brian just submitted to IYS. We'd be working with a post doc on it most likely. A concise lit review might be worth putting together if it takes less than a day and a half or so to get something started. There are other higher priority tasks at the moment tho but lets keep the issue open but in the icebox for now?

**Comment by timvdstap** [comment]
> I think this would fit in with the proposal that Brian just submitted to IYS. We'd be working with a post doc on it most likely. A concise lit review might be worth putting together if it takes less than a day and a half or so to get something started. There are other higher priority tasks at the moment tho but lets keep the issue open but in the icebox for now?

Sounds good - I'll bring up the topic with the SMBD Group as well (again) next week because it would be preferred (required) that the data collected with salmon as sampling instrument can be standardized and hosted on OBIS/GOOS. Should you come across any good scientific papers send them my way please, I'll have a read over! 👍

**Comment by Br-Johnson** [comment]
Sounded like the OBIS community doesn't see it this way, so closing out this issue!
