### ISSUE TITLE
2019 Nutrients

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/iys-oos#7]
Description: Phosphate, silicate, nitrate.
Source Language: Russian
Status: Processed & available as spreadsheet
Group: TINRO
Data Access: NONE

**Comment by jclgan** [comment]
What is the difference between `Bot. depth` and `Depth`?

**Comment by jclgan** [comment]
What units are `[mkM/l]`? Is Si = silicate, DIP = dissolved inorganic phosphate, DIN = dissolved inorganic nitrogen?

**Comment by jclgan** [comment]
The temperature & salinity data in the tab "Hydro_GoA" is identical to the values in "Chemistry_GoA" _with the exception of_ the Hydro tab missing measurements for 0m. Why is that?

**Comment by Br-Johnson** [comment]
Is the nutrients file good to go?

**Comment by timvdstap** [comment]
> Is the nutrients file good to go?

Yes I believe so! Unless you have any comments @jclgan ? I'll close this issue for now.

**Comment by jclgan** [comment]
Nope I'm happy with the state it's in @timvdstap
