### ISSUE TITLE
Make the IYS CKAN Data Catalogue Public

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/iys-oos#82]
The IYS Data Catalogue is meant to be publically accessible. While some metadata records are in draft, and some data are not ready to be shared publicly, we need a workflow that makes metadata records public asap. I think we should just make metadata records public once we are confident in their accuracy along with the link to the data. People now expect that once they send the data to us we are making it public. If there is a reasonable request to embargo the data for some period, we should still publish the metadata asap and after the embargo period, we just put the link to the data in there. If the metadata is still very drafty we can just keep the metadata record private. This should allow us to remove the password to the catalogue and start working with the IYS website developer to link our catalogue from their main IYS website.

@timvdstap thoughts?

TODO:
- [x] Make all datasets private
- [ ] Remove authentication for the IYS catalogue

**Comment by timvdstap** [comment]
@Br-Johnson Yeah I mostly agree! Although  I don't think currently the scientists are sending us their data with the expectation that we're making the data public, perhaps quite the contrary. However, I do think that we can make most, if not all of the 2019 metadata records public, and add link to standardized / processed data at a later stage. Making those metadata records public will also make it easier for us to share them with the data providers for verification. 

For some 2019 data there have already been papers published and I think if that's the case it'll be possible to link to the standardized data on GoogleDrive. For the other data we need to have a clear indication as to when we can publicly share the processed/standardized data.

**Comment by Br-Johnson** [comment]
Good point about the scientists not expecting their data to go public right away for 2019 and 2020 data. For 2022 data, do we want them to send us data if it's not ready to be public? 

Otherwise, sounds good. Do you want to do a review of the metadata and dataset status' or shall I? Happy to do so if it will be possible for me to pick up where you left off in terms of updating (meta)data status. I think I could do that [here](https://docs.google.com/spreadsheets/d/1XytVum4j3z094EvgUTIAQkTXuFJFqUow4snCozHtn-g/edit#gid=817758502), no?

**Comment by timvdstap** [comment]
@Br-Johnson Yeah ideally once the 2022 data is processed and finalized, it would be great if the scientists can send us the data. Because I'm certain that we'll have to format it slightly still to integration to OBIS/ERDDAP, and that would give us some time to do that. 

If you'd like to review the metadata records that'd be great! We can also divide them (you do the biological datasets, I can do the physical datasets?) if there's too many to go through. Once we've reviewed them I think it would be a good idea to get in touch with the data providers/scientists and verify that the information included is correct, before making it public.

**Comment by Br-Johnson** [comment]
Sounds good. I could start with the Biological datasets.

Did you have a workflow in mind for getting the data providers to review the records before they are public? There's no fine-grained control for dataset access (though version 2.9 of CKAN has a new feature called Dataset Collaborators for fine-grained dataset access.) Barring an imminent update to v2.9 here's two ways we could do it:

1) Make all the data sets Private, remove the login requirement to access the catalogue, create data providers a member account so that they can see their private data sets so they can review. Because there is no fine-grained control, 'members' would see all the private data sets.

2) Keep the login requirement to access the catalogue (keeping the entire catalogue private), and provide the generic login credential to access the catalogue to reviewers. Make all the datasets public (rather than keeping some private and some public because we would have to take the additional step to issue member logins to view the private data sets)

I think option 1 makes the most sense and we probably don't need fine-grained control because in my mind it's an advantage that all the Data Providers can see all the other private metadata records so they know what's coming and who to talk to etc. Option 1 works best too for once we actually want the records (and the catalogue generally) public and while we add add new private data sets.

Thoughts? @timvdstap

**Comment by timvdstap** [comment]
@Br-Johnson I didn't have a specific workflow in mind, but I agree that we should go for option 1. Once verified by the data providers we can publish the metadata records. Then once the data is standardized and published to OBIS/ERDDAP, we can include a link to the Standardized Data and the Processed Data.

The Processed Data for 2019 & 2020 are currently in a private Google Drive folder, should we perhaps move these over to the IYS GitHub repo once finalized?

**Comment by Br-Johnson** [comment]
Sure that sounds good. 

I'll go ahead and make all the datasets private, and then ask Matt F. to take off the authentication
