### ISSUE TITLE
2019 Chlorophyll a

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/iys-oos#9]
Description: NONE
Source Language: English
Status: Processed & available as a spreadsheet
Group: UBC
Data Access: NONE

**Comment by jclgan** [comment]
Raw data now available in tidy relational format

**Comment by timvdstap** [comment]
- [ ] host data on ERDDAP
- [ ] document any (metadata) issues when hosting on ERDDAP.

**Comment by timvdstap** [comment]
A preliminary, draft version of the 2019 IYS chlorophyll data has been hosted here: https://goose.hakai.org/hakai-datasets/erddap/info/index.html?page=1&itemsPerPage=1000

The proposed standard naming convention for phaeopigment concentration can be followed here: 
https://github.com/cf-convention/discuss/issues/81

**Comment by Br-Johnson** [comment]
Published on CIOOS Pacific ERDDAP! https://doi.org/10.21966/yxzb-a531
